version: "3"
services:
  service_jekyll:
    image: jekyll/jekyll:4.2.0
    container_name: local_jekyll
    volumes:
      - ./:/srv/jekyll
    command: jekyll serve -s /srv/jekyll --watch --verbose --trace
    init: true
    ports:
      - "4000:4000"
